//! Verifies the `security_headers` middleware (apps/api/src/middleware.rs)
//! emits every header in the documented set on representative responses.
//!
//! Two cases:
//!
//! * `/healthz` — a 200 from a real handler. Covers the success path.
//! * `/no-such-route` — a 404 from the router with no handler involved.
//!   Confirms the layer is truly outermost: even responses generated by
//!   axum itself (router miss) carry the headers, not just handler-built
//!   ones.
//!
//! No DB needed — both routes are stateless.

use axum::{
    body::Body,
    http::{Request, StatusCode, header::HeaderMap},
};
use tower::ServiceExt;

fn assert_security_headers(headers: &HeaderMap) {
    // ADR-004 §F floor.
    assert_eq!(
        headers.get("content-security-policy").unwrap(),
        "default-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'",
    );
    assert_eq!(
        headers.get("strict-transport-security").unwrap(),
        "max-age=63072000; includeSubDomains; preload",
    );
    assert_eq!(headers.get("x-frame-options").unwrap(), "DENY");
    assert_eq!(headers.get("x-content-type-options").unwrap(), "nosniff");
    assert_eq!(
        headers.get("referrer-policy").unwrap(),
        "strict-origin-when-cross-origin",
    );

    // OWASP additions above the §F floor.
    let perms = headers.get("permissions-policy").unwrap().to_str().unwrap();
    // Spot-check a representative sensor + a capability; the full string
    // is asserted indirectly via byte-equal in the middleware constant.
    assert!(perms.contains("camera=()"), "permissions-policy: {perms}");
    assert!(perms.contains("payment=()"), "permissions-policy: {perms}");
    assert_eq!(
        headers.get("cross-origin-resource-policy").unwrap(),
        "same-origin",
    );
    assert_eq!(
        headers.get("cross-origin-opener-policy").unwrap(),
        "same-origin",
    );
    assert_eq!(headers.get("cache-control").unwrap(), "no-store");

    // Deliberately omitted — assert their absence so a future "helpful"
    // change is caught.
    assert!(
        headers.get("x-xss-protection").is_none(),
        "X-XSS-Protection is deprecated; do not emit"
    );
    assert!(
        headers.get("public-key-pins").is_none(),
        "Public-Key-Pins is deprecated; do not emit"
    );
}

#[tokio::test]
async fn healthz_carries_full_security_header_set() {
    let app = flight_academy_api::app_for_test();
    let req = Request::builder()
        .uri("/healthz")
        .body(Body::empty())
        .unwrap();
    let resp = app.oneshot(req).await.unwrap();
    assert_eq!(resp.status(), StatusCode::OK);
    assert_security_headers(resp.headers());
}

#[tokio::test]
async fn router_404_still_carries_full_security_header_set() {
    let app = flight_academy_api::app_for_test();
    let req = Request::builder()
        .uri("/no-such-route")
        .body(Body::empty())
        .unwrap();
    let resp = app.oneshot(req).await.unwrap();
    assert_eq!(resp.status(), StatusCode::NOT_FOUND);
    assert_security_headers(resp.headers());
}
